[package]
name = "ripht-sapi-gauntlet"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
ripht-php-sapi = { path = ".." }
serde = { workspace = true }
serde_json = { workspace = true }

[[bin]]
name = "gauntlet-ripht-smoke"
path = "src/bin/gauntlet-ripht-smoke.rs"

[[bin]]
name = "gauntlet-ripht-modes"
path = "src/bin/gauntlet-ripht-modes.rs"
