# schema: https://github.com/rust-lang/rustfmt/blob/master/Configurations.md

max_width = 80
chain_width = 30
use_field_init_shorthand = true
use_small_heuristics = "Default"
single_line_let_else_max_width = 0
